# -*- coding: utf-8 -*-

from django.db import connections


def dictfetchall (cursor):
	desc = cursor.description
	return [
		dict (zip ([col[0] for col in desc], row))
		for row in cursor.fetchall ()
	]



def get_total_sale ():
	cursor = connections['opos'].cursor ()

	cursor.execute ('SELECT SUM(((TICKETLINES.PRICE + (TICKETLINES.PRICE * TAXES.RATE)) * TICKETLINES.UNITS)) AS SUM FROM TICKETLINES, TAXES WHERE TICKETLINES.TAXID=TAXES.ID;')
	row = cursor.fetchone ()

	return row


def get_customer_ticketlines(customerpk):
	cursor = connections['opos'].cursor ()

#	cursor.execute ('SELECT TICKETLINES.PRODUCT, TICKETLINES.UNITS, TICKETLINES.PRICE, TAXES.RATE, ((TICKETLINES.PRICE + (TICKETLINES.PRICE * TAXES.RATE)) * TICKETLINES.UNITS) AS SUM FROM TICKETLINES, TAXES, TICKETS, CUSTOMERS WHERE TICKETLINES.TAXID=TAXES.ID AND TICKETLINES.TICKET=TICKETS.ID AND TICKETS.CUSTOMER=CUSTOMERS.ID AND CUSTOMERS.ID="123";')


	cursor.execute ('SELECT PRODUCTS.NAME, RECEIPTS.DATENEW, TICKETLINES.TICKET, TICKETLINES.PRODUCT, TICKETLINES.UNITS, TICKETLINES.PRICE, TAXES.RATE, ((TICKETLINES.PRICE + (TICKETLINES.PRICE * TAXES.RATE)) * TICKETLINES.UNITS) AS SUM FROM TICKETLINES, TAXES, TICKETS, CUSTOMERS, RECEIPTS, PRODUCTS WHERE TICKETLINES.TAXID=TAXES.ID AND TICKETLINES.TICKET=TICKETS.ID AND TICKETS.CUSTOMER=CUSTOMERS.ID AND TICKETS.ID=RECEIPTS.ID AND TICKETLINES.PRODUCT=PRODUCTS.ID AND CUSTOMERS.ID=%s ORDER BY RECEIPTS.DATENEW;', [customerpk])
	
	
	rows = dictfetchall (cursor)
	return rows
